add src files

diff --git a/src/github.com/cloudfoundry-incubator/switchboard/bin/test b/src/github.com/cloudfoundry-incubator/switchboard/bin/test
--- a/src/github.com/cloudfoundry-incubator/switchboard/bin/test
+++ b/src/github.com/cloudfoundry-incubator/switchboard/bin/test
@@ -2,15 +2,34 @@
 
 result=0
 
-MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+function get_cpu_count() {
+  if [[ "$(uname)" = "Darwin" ]]; then
+    sysctl -n hw.ncpu
+  else
+    nproc
+  fi
+}
 
 echo -e "\nVetting packages for potential issues..."
-$MY_DIR/govet
-let "result+=$?"
+"${my_dir}/govet"
 
 echo -e "\nTesting packages..."
-ginkgo -p -r -race -failOnPending -randomizeAllSpecs "$@" $MY_DIR/..
-let "result+=$?"
 
-echo -e "\nExit Code: $result"
-exit $result
+# due to the high amount of concurrency in these tests, tests will often fail
+# with timeouts if run in parallel on systems with fewer than 4 cores
+GINKGO_FLAGS="-r -failOnPending -randomizeAllSpecs -slowSpecThreshold=20 -race -keepGoing"
+if [ "$(get_cpu_count)" -ge "4" ]; then
+  GINKGO_FLAGS="${GINKGO_FLAGS} -p"
+fi
+
+pushd "${my_dir}/.." > /dev/null
+  # shellcheck disable=SC2086
+  ginkgo ${GINKGO_FLAGS} "$@"
+
+  let "result+=$?"
+
+  echo -e "\nExit Code: $result"
+  exit $result
+popd > /dev/null
